Repository TR-42/minishell, pull requests merged in 2023-06, with the labels that each got.

#52 Pipe / Redirectによるスクリプト入力に対応
  srcs/main.c
Labels: Low Priority

#55 mainでbuiltinを実行した時の戻り値を修正
  srcs/childs/_exec_ch_proc_info_arr.c
  srcs/childs/exec_cmd.c
  srcs/main.c
Labels: bug

#58 cd実行時に`PWD`も更新するようにした
  srcs/builtin/cd.c
Labels: bug

#60 存在しない変数にargvを生成しないようにした
  headers/_build_cmd.h
  srcs/build_cmd/_get_argc.c
  srcs/build_cmd/build_cmd.c
  srcs/childs/env_util.c
Labels: bug

#62 `heap-use-after-free`を起こさないようにした
  srcs/builtin/_environ_utils.c
Labels: bug

#65 heredoc失敗時にtmpfileを削除するようにした
  srcs/childs/_parse_exec.c
  srcs/heredoc/create_tmpfile.c
  srcs/heredoc/rm_tmpfile.c
Labels: bug

#75 DQUOTE終了の直前に `$?` が存在した場合に、DQUOTEのスペースが無視されるバグを修正
  .tests/test_build_cmd.c
  Makefile
  srcs/serializer/_serializer_var.c
Labels: bug

#78 通常のTerminalにてCtrl+Cを2回押さないと改行されないバグを修正
  srcs/signal_handling/init_sig_handler.c
Labels: bug

#81 古いFDをCloseするかの判定でIN/OUTの指定をミスしていたので修正
  srcs/childs/_redirect.c
Labels: bug

#85 EOFによる終了時に `exit` を表示するようにした
  srcs/main.c
Labels: bug, Low Priority

#87 Builtinに関するさまざまなバグを修正した
  Makefile
  srcs/builtin/_environ_utils.c
  srcs/builtin/_pwd.h
  srcs/builtin/_util_commands.h
  srcs/builtin/cd.c
  srcs/builtin/echo.c
  srcs/builtin/exec_builtin.c
  srcs/builtin/exit.c
  srcs/builtin/export.c
  srcs/builtin/pwd.c
  srcs/builtin/save_environ.c
  srcs/builtin/save_pwd.c
Labels: bug

#90 コマンドが見つからなかったときにエラーが二重で出るバグを修正
  srcs/childs/exec_cmd.c
Labels: bug

#91 ビルトインの修正を改めて反映
  srcs/builtin/_pwd.h
  srcs/builtin/cd.c
  srcs/builtin/exit.c
  srcs/builtin/pwd.c
  srcs/builtin/save_environ.c
  srcs/builtin/save_pwd.c
Labels: bug

#93 コンパイルエラーを修正
  headers/error_utils.h
Labels: bug
